import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Banner from '@/components/Banner';
import Image from 'next/image';
import Card from '@/components/card';

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log('Hi banner button');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src='/static/hero-img.png' width={300} height={300} />
        </div>
        <Card
          name='DarkHorse Coffee'
          imgUrl='/static/hero-img.png'
          href='/coffee-store/darkhorse-coffee'
        />
      </main>
    </div>
  );
}
